### PR TITLE
CCF unit update

### PR DESCRIPTION
**Pull request by maryarbab**
**Is this a new addition or an update to an existing factor?**

- [ ] Update

**What category or categories does it affect?**

_CCF_

**What?**

_Update Memory and Storage including the time constrain_

**Why?**

_To be consistent with the methodology_

### CODE REVIEW

**Review by GeeWee — DISMISSED** [review]
Matches my understanding, but I'll defer to Pat or Isis for the final judgement. @Isis note that I don't think have a unit for `gb-hour` in the API currently.

**Comment by grindcode** [comment]
@GeeWee you are right, we will need to add that unit. Question is if this turns into a breaking change or defaults will handle the cases where no time is defined for storage.

**Review by grindcode — APPROVED** [review]

**Comment by GeeWee** [comment]
@grindcode it will be a breaking change, but I think we can consider it a bugfix - as the old numbers are _wrong_

**Review by GeeWee — APPROVED** [review]
new lca changes look good to me!

**Pull request merged**
