### PR TITLE
add m flag in GHGP data

### PR DESCRIPTION
**Pull request by gpantelidou**
**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

All the categories that GHG Protocol covers

**What?**

Flag the data with a methodological `m` warning and add appropriate descirption note. Please remember that some GHGP data already have other flags like `e` or `p.` 

**Why?**

GHG Protocol removed the data from their website - so we try to notify the users

### CODE REVIEW

**Review by AnastasiaLobanova — APPROVED** [review]
looks good to me!

**Comment by patstirling** [comment]
Ah - these flags should no apply to the GHG/quantis dataset (they are still hosted). Also could we please change "WARNING" to "NOTE" and change "replaced" to "removed"?

**Review by patstirling — CHANGES_REQUESTED** [review]
See comment

**Comment by gpantelidou** [comment]
Oh! I thought it was for all the data that we cite under GHG protocol. Thanks @patstirling I will fix this now.

**Review by patstirling — APPROVED** [review]

**Pull request merged**
