### PR TITLE
eGrid residual mix & location-based/ Add scope to electricity EFs

### PR DESCRIPTION
**Pull request by maryarbab**
**Is this a new addition or an update to an existing factor?**

- [X] New
- [X] Update

**What category or categories does it affect?**

_Electricity_

**What?**

_Adding eGrid subregion 2021 residual mix and location-based data. Add scopes for all electricity EFs_

**Why?**

_To have both market-based and location-based data for the US_

### CODE REVIEW

**Comment by TimCroker** [comment]
Can we add dataset creation dates?
EPA E-Grid: 23/02/21
Green-E: 14/04/2021

**Comment by TimCroker** [comment]
Can we add dataset creation dates?
EPA E-Grid: 23/02/21
Green-E: 14/04/2021

**Comment by maryarbab** [comment]
> 14/04/2021

@TimCroker @AnastasiaLobanova @gpantelidou let's have a quick discussion about dataset names structure today.

**Review by AnastasiaLobanova — APPROVED** [review]
Thank you @maryarbab - huge effort!

Some questions I have:
- DISER has lca_activity as electricity_consumption is this correct?
- Why for GHG Protocol we have scope 2|3 for the lca boundary: electricity_generation?

Rest looks good to me!

**Comment by maryarbab** [comment]
> Thank you @maryarbab - huge effort!
> 
> Some questions I have:
> 
> * DISER has lca_activity as electricity_consumption is this correct?
> * Why for GHG Protocol we have scope 2|3 for the lca boundary: electricity_generation?
> 
> Rest looks good to me!

Thank you, @AnastasiaLobanova ! Regardign your questions:
1- That is the term DISER uses, so I think it should be Ok.
2- That is same issue I raised [here](https://linear.app/climatiq/issue/SCI-80/add-scope-to-all-oefdb-electricity-efs), so I agree to have only scope 2 here.  As they seem to be IEA numbers.

**Review by AnastasiaLobanova — DISMISSED** [review]

**Review by AnastasiaLobanova — APPROVED** [review]

**Pull request merged**
