### PR TITLE
Clarify unique-making fields in Readme

### PR DESCRIPTION
**Pull request by platy**
**What?**

Make readme more clear about `lca_activity` being part of the set of fields which make an EF unique.

It looks to me that lca_activity was added but not all the places were updated in the readme

**Why?**

Currently depending on which part of the readme you read, you may or may not think that lca_activity contributes tot he unique key of the EF.

### CODE REVIEW

**Comment by platy** [comment]
Validation error was because I was branched from a few weeks ago, I've rebased to fix

**Comment by AnastasiaLobanova** [comment]
@patstirling @platy are we still working on this PR?

**Comment by platy** [comment]
@AnastasiaLobanova I still think this little doc fix is worth merging - it's just waiting on a review

**Review by patstirling — CHANGES_REQUESTED** [review]
See edits - also wherever we have `year_valid` we will need to have `year_valid_from`

**Comment by platy** [comment]
Wow, the year columns have changed twice since I opened this PR, additionally I see that in [data guidance](https://github.com/climatiq/Open-Emission-Factors-DB/blob/main/DATA_GUIDANCE.md#years_valid) it says `years_valid`.
The commits in this PR are now totally irrelevant, I'm closing this PR

**Pull request closed without merging**
